config/routes.rb
Rails.application.routes.draw do
  resources :notes

  #routes for users
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  #routes for login form
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  #for categories
  resources :categories, except: [:destroy]

  #root
  root to:'users#index'


end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :note_categories
  has_many :categories, through: :note_categories

  validates :title, presence: true, length: { in: 2..50 }
  validates :description, presence: true, length: { in: 10..1000 }
  validates :user_id, presence: true
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  # GET /notes
  # GET /notes.json
  PER = 5

  def index
    @notes = Note.page(params[:page]).per(PER)
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create  
    @note = Note.new(note_params)
    @note.user = current_user 
    if @note.save
      flash[:success] = "Note was created"
      redirect_to note_path(@note)
    else 
      render 'new'
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :description)
    end

    def require_same_user
      if current_user != @note.user and !current_user.admin?
        flash[:notice] = " You do not have access privileges to do this action"
        redirect_to signup_path
      end
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/edit.html.erb
<div id = "error_msg">
  <h3><%= pluralize(@note.errors.count, "error") if @note.errors.any? %></h3>
  <ul>
    <% @note.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

<div class = "container text-center">
  <div class = "note-edit row">
    <div class = "form col-sm-12">
      <h2>Edit note</h2>
      <%= form_with(model: @note, local: true) do |f| %>
        <p>
          <%= f.label :title, :class => 'form-inline' %>
          <%= f.text_field :title, id: :note_title, :class => 'form-control' %>
        </p>
        <p>
          <%= f.label :description, :class => 'form-inline' %>
          <%= f.text_area :description, id: :note_description, :class => 'form-control' %>
        </p>
        <p>
          <%= f.submit class: "btn btn-outline-info" %>
        </p>
      <% end %>
      <p class = "show-back">
        <%= link_to 'Note', @note, :class => 'show-btn' %> |
        <%= link_to 'Back', notes_path, :class => 'show-btn' %>
      </p>
    </div>
  </div>
</div>

app/views/notes/index.html.erb
<h3 class = "text-center all-notes-title">All Notes</h3>
<hr class = all-notes-hr>
<div class = "container-fluid">
  <% @notes.each do |note| %>
    <div class = "row">
      <div class = "all-notes col-sm-12">
        <ul>
          <div class = "note-titile">
            <li>Title: <%= link_to truncate(note.title, length: 100), note_path(note) %></li>
          </div>
          <div class = "note-body">
            <li>Description: <%= truncate(note.description, length: 100) %></li>
          </div>
          <div class = "note-author">
            <li>Author: <%= note.user.name %></li>
          </div>
          <div class = "note-actions">
            <%= link_to "edit this note", edit_note_path(note), class: "btn btn-xs btn-outline-info" %>
            <%= link_to "delete this note", note_path(note), method: :delete, data: {confirm: "are you sure you want to delete this note?"}, class: "btn btn-xs btn-outline-danger" %>
          </div>
        </ul>
        <hr>
      </div>
    </div>
  <% end %>
    <%= paginate @notes, :class => 'pagination' %>
  <div class = "row">
    <div class = "new-note col-sm-12">
      <%= link_to "New Note", new_note_path, :class => 'btn btn-outline-light new-btn' %>
    </div>
  </div>
</div>

app/views/notes/new.html.erb
<div id = "error_msg">
  <h3><%= pluralize(@note.errors.count, "error") if @note.errors.any? %></h3>
  <ul>
    <% @note.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

<div class = "container text-center">
  <div class = "note-edit row note-new">
    <div class = "form col-sm-12">
      <h2>New note</h2>
      <%= form_with(model: @note, local: true) do |f| %>
        <p>
          <%= f.label :title, :class => 'form-inline' %>
          <%= f.text_field :title, id: :note_title, :class => 'form-control' %>
        </p>
        <p>
          <%= f.label :description, :class => 'form-inline' %>
          <%= f.text_area :description, id: :note_description, :class => 'form-control' %>
        </p>
        <p>
          <%= f.submit class: "btn btn-outline-info" %>
        </p>
        <p>
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cd| %>
            <% cd.label(class: "checkbox-inline input_checkbox") {cd.check_box(class: "checkbox") + cd.text} %>
          <% end %>
        </p>
      <% end %>
      <p class = "show-back">
        <%= link_to 'Back', notes_path, :class => 'show-btn' %>
      </p>
    </div>
  </div>
</div>

app/views/notes/show.html.erb
<h3 class = "text-center show-title"><%= @note.title %></h3>
<div class = "container-fluid note-show">
  <div class = "row">
    <div class = "col-sm-12">
      <p>
        <%= @note.description %>
      </p>
      <p class = "author">
        <strong>Written by: </strong>
        <%= @note.user.name %>
      </p>
      <div class = "row note-btn">
      <% if logged_in? && (current_user == @note.user || current_user.admin?) %>
        <%= link_to 'Edit', edit_note_path(@note), :class => 'btn btn-outline-info col-sm-3' %>
        <%= link_to 'Delete', note_path(@note), method: :delete, data: {confirm: "You want to delete this note?"}, :class => 'btn btn-outline-danger col-sm-3' %>
      <% end %>
        <%= link_to 'Back', notes_path, :class => 'btn btn-outline-light col-sm-3' %>
    </div>
    </div>
  </div>
</div>