config/routes.rb
Rails.application.routes.draw do
  resources :notes

  #routes for users
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  #routes for login form
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  #for categories
  resources :categories, except: [:destroy]

  #root
  root to:'users#index'


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :notes, dependent: :destroy
  has_one_attached :image #should i delete this or not
  before_save { self.email = email.downcase }

  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { in: 2..20 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, confirmation: true, uniqueness: { case_sensitive: false }, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }

  validates :email_confirmation, presence: true

  validates :password, presence: true, on: :create, confirmation: true, length: { in: 8..16 }

  validates :password_confirmation, presence: true, on: :create

  # validate :image_type


  def image_type
    if image.attached? && image.content_type.in?(%("image/jpeg image/png"))
      errors.add(:image, 'error message')
    elsif !image.attached?
      errors.add(:image, 'error message')
    end
  end

  # def profile_image
  #   return self.variant(resize: '300x300').processed
  # end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  # before_action :require_admin, only: [:destroy]
  after_action :require_login, only: :new
  before_action :login_prohibited, :only => [:new, :create]
  
  def new 
    @user = User.new
  end
  def create 
    @user = User.create params.require(:user).permit(:name, :email, :email_confirmation, :password, :password_confirmation, :image)
    if @user.save
      flash[:success] = "User was successfully created"
      redirect_to login_path
    else 
      render 'new'
    end
  end
  def index
    @users = User.all
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update params.require(:user).permit(:name, :email, :email_confirmation, :image)
      flash[:success] = "Has been updated successfully"
      redirect_to current_user
    else
      render 'edit'
    end
  end
  def show 
    @user = User.find(params[:id])
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "user was deleted"
    redirect_to login_path
  end


  private 
  def user_params
    params.require(:user).permit(:name, :email, :email_confirmation, :password, :password_confirmation)
  end
  def require_same_user
    if current_user != current_user and !current_user.admin?
      flash[:danger] = "only edit or delete are allowed"
      redirect_to login_path
    end
  end


  # def require_admin
  #   if logged_in? and !current_user.admin?
  #     flash[:danger] = "you are not admin user"
  #     redirect_to login_path
  #   end
  # end
  # def post_params
  #   params.require(:post).permit(:image, :name, :email)
  # end
end

app/views/users/_errors.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this note from being created user:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class = "container text-center">
  <div class = "row edit_user">
      <div id = "error_msg">
        <h3><%= pluralize(@user.errors.count, "error") if @user.errors.any? %></h3>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <div class = "edit_form">
        <h3>edit your user</h3>
        <%= form_with model: @user, local: true do |f| %>
          <p>
            <%= f.label :name, :class => 'form-inline' %>
            <%= f.text_field :name, id: :user_name, :class => 'form-control' %>
          </p>
          <p>
            <%= f.label :email, :class => 'form-inline' %>
            <%= f.text_field :email, id: :user_email, :class => 'form-control' %>
          </p>
          <p>
            <%= f.label :email_confirmation, :class => 'form-inline' %>
            <%= f.text_field :email_confirmation, id: :user_email_confirmation, :class => 'form-control' %>
          </p>
          <p>
            <%= f.file_field :image, :class => 'form-inline image-file' %>
          </p>
          <p>
            <%= f.submit class: "btn btn-outline-info form-control submit" %>
          </p>
        <% end %>
      </div>
      <p class = "back-link">
        <%= link_to 'Back to profile', current_user, :class => 'back' %>
      </p>
  </div>
</div>

app/views/users/index.html.erb
<div class="jumbotron jumbotron-fluid ">
  <div class="container">
    <h1 class="display-4 text-center">Blognote</h1>
    <div class = "text-center">
      <%= image_tag('woman-3190829_1280.jpg') %>
    </div>
    <p class="lead text-center">Just take notes as you write a blog.</p>
  </div>
</div>

<div class = "container">
<div class = "signuptext row">

  <div class = "registration form-inline col-sm-6">
    <h3>Register</h3>
    <div class = "signuptext-btn">
      <%= link_to 'Sign Up', signup_path, class: 'btn btn-outline-light' %>
    </div>
  </div>

    <div class = "loginform form-inline col-sm-6">
      <h3 class>Log in</h3>
      <div class = "loginform-btn">
        <%= link_to 'Log in', login_path, class: 'btn btn-outline-info' %>
      </div>
    </div>
  
</div>
</div>

<div class = "body">
  <div class = "container col-sm-12">
    <h1>Welcome to Blognote</h1>
    <p>Blognote, as you see, combined with <br>"Blog" and "Note", you can take notes as you blog.</p>
    <p>Easy to share your notes. Even you skipped class, just login and see your classmate's note.</p>
    <p>It's time to stop buying stationaries.
    <br>Now save your money, it's free for anyone.</p>
  </div>
</div>

app/views/users/new.html.erb
<div id = "error_msg">
  <h3><%= pluralize(@user.errors.count, "error") if @user.errors.any? %></h3>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

<div class = "container text-center">
  <div class = "signup row">
    <div class = "form col-sm-12">
      <h2>Sign Up</h2>
      <%= form_with(model: @user, local: true) do |f| %>
        <p>
          <%= f.label :name, :class => 'form-inline' %>
          <%= f.text_field :name, id: :user_name, :class => 'form-control' %>
        </p>
        <p>
          <%= f.label :email, :class => 'form-inline' %>
          <%= f.text_field :email, id: :user_email, :class => 'form-control' %>
        </p>
        <p>
          <%= f.label :email_confirmation, :class => 'form-inline' %>
          <%= f.text_field :email_confirmation, id: :user_email_confirmation, :class => 'form-control' %>
        </p>
        <p>
          <%= f.label :password, :class => 'form-inline' %>
          <%= f.password_field :password, :class => 'form-control' %>
        </p>
        <p>
          <%= f.label :password_confirmation, :class => 'form-inline' %>
          <%= f.password_field :password_confirmation, :class => 'form-control' %>
        </p>
        <p class = "imagefield">
          <%= f.file_field :image %>
        </p>
        <p>
          <%= f.submit class: "btn btn-outline-info" %>
        </p>
      <% end %>

      <p class = "youhaveanaccount">
        <%= link_to 'you have an account? Log in now.', login_path, :class => 'linktologin' %>
      </p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class = "container">
  <div class = "row">
    <div class = "profile col-sm-12">
    <h3>Profile</h3>
      <ul>
        <li>
          <strong>Name:</strong>
          <%= @user.name %>
        </li>
        <li>
          <strong>Email:</strong>
          <%= @user.email %>
        </li>
        <li>
          <% if @user.image.attached? %>
            <% image_tag @user.image %> <%# temporary commented out %>
          <% end %>
        </li>
        <li>
          <strong><%= link_to 'See all notes', notes_path, :class => 'seenotes' %></strong>
        </li>
          <% if logged_in? && (current_user == @user || current_user.admin?) %>
            <%= link_to "New Note", new_note_path, :class => 'btn btn-outline-primary col-sm-12' %>
            <%= link_to 'Edit', edit_user_path(@user), :class => 'btn btn-outline-info col-sm-12' %><br>
            <%= link_to 'Delete', user_path(@user), method: :delete, data: {confirm: "Are you sure you want to delete this user?"}, :class => 'btn btn-outline-danger col-sm-12' %><br>
          <% end %>
            <%= link_to 'Back', users_path, :class => 'btn btn-outline-light col-sm-12' %>
      </ul>
    </div>
  </div>
</div>